services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"   # localhost:80 로 접근 (외부로 공개되는 유일한 포트)
    env_file:
      - .env        # BACKEND_PRIVATE_IP, ML_PRIVATE_IP
    depends_on:
      frontend:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [uhok_net]
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "50m", max-file: "3" }

  frontend:
    build:
      context: ../../uhok-frontend
      dockerfile: Dockerfile
    image: uhok-frontend:3.0.0
    environment:
      - CI=false  # ESLint 경고를 오류로 처리하지 않도록 설정
    expose:
      - "80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [uhok_net]
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "50m", max-file: "3" }

networks:
  uhok_net:
    external: true
